# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weather-bot-tester
  namespace: weather-bot-tester
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: weather-bot-tester
    spec:
      containers:
        - image: informaticslab/weather-bot-tester:latest
          imagePullPolicy: ifMissing
          name: weather-bot-tester
          env:
            - name: DIRECT_LINE_SECRET
              valueFrom:
                secretKeyRef:
                  name: weather-bot-tester
                  key: DIRECT_LINE_SECRET
            - name: BOT_TESTS_FILE
              value: /tmp/bot-tests/tests.json
          resources:
            requests:
              cpu: 10m
              memory: 30Mi
