# Deployment
apiVersion: batch/v1
kind: Job
metadata:
  name: weather-bot-tester
  namespace: weather-bot-tester
spec:
  parallelism: 100
  completions: 100
  template:
    metadata:
      labels:
        app: weather-bot-tester
    spec:
      restartPolicy: OnFailure
      containers:
        - image: informaticslab/weather-bot-tester:v0.3.0
          imagePullPolicy: IfNotPresent
          name: weather-bot-tester
          env:
            - name: DIRECT_LINE_SECRET
              valueFrom:
                secretKeyRef:
                  name: weather-bot-tester
                  key: DIRECT_LINE_SECRET
            - name: BOT_TESTS_FILE
              value: /tmp/bot-tests/tests.json
          resources:
            requests:
              cpu: 10m
              memory: 30Mi
          volumeMounts:
            - mountPath: "/tmp/bot-tests"
              name: bot-tests
      volumes:
        - name: bot-tests
          configMap:
            name: weather-bot-tester
